[package]
name = "tintedglass-renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.19.1", features = ["bevy_dev_tools", "debug", "dynamic_linking", "webgpu"] }
bevy_web_file_drop = "0.4.0"
itertools.workspace = true
log = { version = "0.4.34" }
tintedglass-model.workspace = true
