[workspace]
resolver = "3"
members = ["tintedglass-model", "tintedglass-renderer"]

[workspace.dependencies]
snafu = "0.9.2"
tintedglass-model = { path = "tintedglass-model" }

[profile.dev]
opt-level = 1
debug = "line-tables-only"

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = "thin"
codegen-units = 1

[profile.wasm-release]
inherits = "release"
opt-level = "s"
strip = "debuginfo"
