[package]
name = "lowmist-schematic"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.25.2"
clap.workspace = true
fastnbt = { git = "https://github.com/zdragg/fastnbt" }
flate2 = "1.1.10"
glam.workspace = true
indexmap = "2.14.2"
itertools.workspace = true
jiff = { version = "0.2.37", features = ["serde"] }
serde = "1.0.229"
snafu.workspace = true
