[package]
name = "lowmist-schematic"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.25.2"
clap.workspace = true
fastnbt = "2.6.3"
flate2 = "1.1.10"
glam = { version = "0.32.1", features = ["serde"] }
indexmap = "2.14.2"
itertools.workspace = true
jiff = { version = "0.2.37", features = ["serde"] }
serde = "1.0.229"
snafu.workspace = true
